-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 18:35:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Ex2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ex2` ;

-- -----------------------------------------------------
-- Schema Ex2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ex2` DEFAULT CHARACTER SET latin1 ;
USE `Ex2` ;

-- -----------------------------------------------------
-- Table `Ex2`.`ProvInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ex2`.`ProvInfo` ;

CREATE TABLE IF NOT EXISTS `Ex2`.`ProvInfo` (
  `ProvNo` VARCHAR(2) NOT NULL,
  `ProvSpecialty` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ProvNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ex2`.`PatInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ex2`.`PatInfo` ;

CREATE TABLE IF NOT EXISTS `Ex2`.`PatInfo` (
  `PatNo` VARCHAR(2) NOT NULL,
  `PatAge` INT(11) NOT NULL,
  `PatCity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PatNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ex2`.`VisitInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ex2`.`VisitInfo` ;

CREATE TABLE IF NOT EXISTS `Ex2`.`VisitInfo` (
  `VisitNo` VARCHAR(6) NOT NULL,
  `VisitDate` DATE NOT NULL,
  `PatInfo_PatNo` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`VisitNo`, `PatInfo_PatNo`),
  INDEX `fk_VisitInfo_PatInfo1_idx` (`PatInfo_PatNo` ASC) ,
  CONSTRAINT `fk_VisitInfo_PatInfo1`
    FOREIGN KEY (`PatInfo_PatNo`)
    REFERENCES `Ex2`.`PatInfo` (`PatNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ex2`.`VisitDiagnosis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ex2`.`VisitDiagnosis` ;

CREATE TABLE IF NOT EXISTS `Ex2`.`VisitDiagnosis` (
  `VisitInfo_VisitNo` VARCHAR(6) NOT NULL,
  `ProvInfo_ProvNo` VARCHAR(2) NOT NULL,
  `Diagnosis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VisitInfo_VisitNo`, `ProvInfo_ProvNo`),
  INDEX `fk_BigPatientTable_ProvInfo1_idx` (`ProvInfo_ProvNo` ASC) ,
  INDEX `fk_BigPatientTable_VisitInfo1_idx` (`VisitInfo_VisitNo` ASC) ,
  CONSTRAINT `fk_BigPatientTable_ProvInfo1`
    FOREIGN KEY (`ProvInfo_ProvNo`)
    REFERENCES `Ex2`.`ProvInfo` (`ProvNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BigPatientTable_VisitInfo1`
    FOREIGN KEY (`VisitInfo_VisitNo`)
    REFERENCES `Ex2`.`VisitInfo` (`VisitNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
